/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Branch = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const Time = IDL.Int;
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Text,
  'followUpType' : IDL.Text,
  'assignedTo' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : Time,
  'leadId' : IDL.Text,
  'notes' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'source' : IDL.Text,
  'assignedAgent' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'gradeLevel' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadSource = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'branchId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBranch' : IDL.Func([Branch], [IDL.Text], []),
  'addCampaign' : IDL.Func([Campaign], [IDL.Text], []),
  'addFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
  'addLead' : IDL.Func([Lead], [IDL.Text], []),
  'addLeadSource' : IDL.Func([LeadSource], [IDL.Text], []),
  'addTeamMember' : IDL.Func([TeamMember], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBranch' : IDL.Func([IDL.Text], [], []),
  'deleteCampaign' : IDL.Func([IDL.Text], [], []),
  'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
  'deleteLead' : IDL.Func([IDL.Text], [], []),
  'deleteLeadSource' : IDL.Func([IDL.Text], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getLeadSources' : IDL.Func([], [IDL.Vec(LeadSource)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
      [
        IDL.Opt(
          IDL.Record({
            'username' : IDL.Text,
            'name' : IDL.Text,
            'role' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBranch' : IDL.Func([Branch], [], []),
  'updateCampaign' : IDL.Func([Campaign], [], []),
  'updateFollowUp' : IDL.Func([FollowUp], [], []),
  'updateLead' : IDL.Func([Lead], [], []),
  'updateLeadSource' : IDL.Func([LeadSource], [], []),
  'updateTeamMember' : IDL.Func([TeamMember], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Branch = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const Time = IDL.Int;
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Text,
    'followUpType' : IDL.Text,
    'assignedTo' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : Time,
    'leadId' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'source' : IDL.Text,
    'assignedAgent' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'gradeLevel' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadSource = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBranch' : IDL.Func([Branch], [IDL.Text], []),
    'addCampaign' : IDL.Func([Campaign], [IDL.Text], []),
    'addFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
    'addLead' : IDL.Func([Lead], [IDL.Text], []),
    'addLeadSource' : IDL.Func([LeadSource], [IDL.Text], []),
    'addTeamMember' : IDL.Func([TeamMember], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBranch' : IDL.Func([IDL.Text], [], []),
    'deleteCampaign' : IDL.Func([IDL.Text], [], []),
    'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
    'deleteLead' : IDL.Func([IDL.Text], [], []),
    'deleteLeadSource' : IDL.Func([IDL.Text], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getLeadSources' : IDL.Func([], [IDL.Vec(LeadSource)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
        [
          IDL.Opt(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBranch' : IDL.Func([Branch], [], []),
    'updateCampaign' : IDL.Func([Campaign], [], []),
    'updateFollowUp' : IDL.Func([FollowUp], [], []),
    'updateLead' : IDL.Func([Lead], [], []),
    'updateLeadSource' : IDL.Func([LeadSource], [], []),
    'updateTeamMember' : IDL.Func([TeamMember], [], []),
  });
};

export const init = ({ IDL }) => { return []; };