/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branch { 'id' : string, 'name' : string, 'location' : string }
export interface Campaign {
  'id' : string,
  'status' : string,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
}
export interface FollowUp {
  'id' : string,
  'followUpType' : string,
  'assignedTo' : string,
  'completed' : boolean,
  'dueDate' : Time,
  'leadId' : string,
  'notes' : string,
}
export interface Lead {
  'id' : string,
  'status' : string,
  'source' : string,
  'assignedAgent' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'gradeLevel' : string,
  'notes' : string,
  'phone' : string,
}
export interface LeadSource { 'id' : string, 'name' : string }
export interface TeamMember {
  'id' : string,
  'name' : string,
  'role' : string,
  'branchId' : string,
}
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBranch' : ActorMethod<[Branch], string>,
  'addCampaign' : ActorMethod<[Campaign], string>,
  'addFollowUp' : ActorMethod<[FollowUp], string>,
  'addLead' : ActorMethod<[Lead], string>,
  'addLeadSource' : ActorMethod<[LeadSource], string>,
  'addTeamMember' : ActorMethod<[TeamMember], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBranch' : ActorMethod<[string], undefined>,
  'deleteCampaign' : ActorMethod<[string], undefined>,
  'deleteFollowUp' : ActorMethod<[string], undefined>,
  'deleteLead' : ActorMethod<[string], undefined>,
  'deleteLeadSource' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'getLeadSources' : ActorMethod<[], Array<LeadSource>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [{ 'username' : string, 'password' : string }],
    [] | [{ 'username' : string, 'name' : string, 'role' : string }]
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBranch' : ActorMethod<[Branch], undefined>,
  'updateCampaign' : ActorMethod<[Campaign], undefined>,
  'updateFollowUp' : ActorMethod<[FollowUp], undefined>,
  'updateLead' : ActorMethod<[Lead], undefined>,
  'updateLeadSource' : ActorMethod<[LeadSource], undefined>,
  'updateTeamMember' : ActorMethod<[TeamMember], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];