/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Branch { 'id' : string, 'name' : string, 'location' : string }
export interface CalendarEvent {
  'id' : string,
  'title' : string,
  'date' : string,
  'color' : string,
  'category' : string,
}
export interface Campaign {
  'id' : string,
  'status' : string,
  'name' : string,
  'createdAt' : string,
  'description' : string,
}
export interface CampaignSend {
  'id' : string,
  'leadName' : string,
  'templateId' : string,
  'note' : string,
  'campaignId' : string,
  'sentAt' : string,
  'sentBy' : string,
  'leadId' : string,
}
export interface CampaignTemplate {
  'id' : string,
  'name' : string,
  'createdAt' : string,
  'mediaUrl' : string,
  'messageText' : string,
  'mediaType' : string,
}
export interface FollowUp {
  'id' : string,
  'followUpType' : string,
  'assignedTo' : string,
  'completed' : boolean,
  'dueDate' : string,
  'leadId' : string,
  'notes' : string,
}
export interface IntegrationConfig {
  'emailProvider' : string,
  'whatsappAccessToken' : string,
  'emailFromAddress' : string,
  'emailApiKey' : string,
  'whatsappApiUrl' : string,
  'whatsappPhoneNumberId' : string,
  'emailFromName' : string,
  'websiteWebhookSecret' : string,
  'metaWebhookVerifyToken' : string,
}
export interface Lead {
  'id' : string,
  'status' : string,
  'source' : string,
  'assignedAgent' : string,
  'name' : string,
  'createdAt' : string,
  'email' : string,
  'gradeLevel' : string,
  'notes' : string,
  'phone' : string,
}
export interface LeadActivity {
  'id' : string,
  'activityType' : string,
  'description' : string,
  'leadId' : string,
  'performedBy' : string,
  'timestamp' : string,
}
export interface LeadNote {
  'id' : string,
  'content' : string,
  'createdAt' : string,
  'createdBy' : string,
  'leadId' : string,
}
export interface LeadSource { 'id' : string, 'name' : string }
export interface ReportCard {
  'id' : string,
  'studentId' : string,
  'subjects' : Array<SubjectGrade>,
  'date' : string,
  'overallGrade' : string,
  'term' : string,
  'academicYear' : string,
  'attendance' : string,
  'teacherComment' : string,
}
export interface SchoolUpdate {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : string,
  'category' : string,
}
export interface Student {
  'id' : string,
  'name' : string,
  'admissionNumber' : string,
  'grade' : string,
  'parentUsername' : string,
}
export interface StudentRecord {
  'id' : string,
  'rollNumber' : string,
  'name' : string,
  'grade' : string,
  'branchId' : string,
  'parentName' : string,
  'parentContact' : string,
  'parentEmail' : string,
  'dateOfBirth' : string,
  'address' : string,
  'admissionNumber' : string,
}
export interface SubjectGrade {
  'marks' : string,
  'subject' : string,
  'grade' : string,
  'remarks' : string,
}
export interface Task {
  'id' : string,
  'title' : string,
  'assignedTo' : string,
  'createdAt' : string,
  'completed' : boolean,
  'dueDate' : string,
  'description' : string,
  'leadId' : string,
  'priority' : string,
}
export interface Teacher {
  'id' : string,
  'username' : string,
  'subjects' : string,
  'name' : string,
  'grade' : string,
  'branchId' : string,
}
export interface TeamMember {
  'id' : string,
  'name' : string,
  'role' : string,
  'branchId' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhatsAppMessageResult {
  'message' : string,
  'success' : boolean,
}
export interface Worksheet {
  'id' : string,
  'title' : string,
  'subjects' : Array<WorksheetSubject>,
  'date' : string,
  'teacherName' : string,
  'grade' : string,
}
export interface WorksheetSubject {
  'subject' : string,
  'homework' : string,
  'activities' : string,
  'notes' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface StaffProfile {
  'id' : string,
  'name' : string,
  'designation' : string,
  'contactNumber' : string,
  'branchId' : string,
  'role' : string,
  'dailyActivities' : string,
  'notes' : string,
  'email' : string,
}
export interface UserAccount {
  'id' : string,
  'username' : string,
  'password' : string,
  'role' : string,
  'fullName' : string,
  'email' : string,
}
export interface WhatsAppMessage {
  'id' : string,
  'leadId' : string,
  'leadName' : string,
  'leadPhone' : string,
  'direction' : string,
  'messageText' : string,
  'status' : string,
  'timestamp' : string,
  'messageId' : string,
  'campaignId' : string,
}
export interface StaffAttendance {
  'id' : string,
  'staffId' : string,
  'staffName' : string,
  'branchId' : string,
  'date' : string,
  'status' : string,
  'markedBy' : string,
  'timestamp' : string,
}
export interface TeacherPerformanceRecord {
  'id' : string,
  'teacherId' : string,
  'teacherName' : string,
  'branchId' : string,
  'month' : string,
  'year' : string,
  'activitiesUploaded' : bigint,
  'worksheetsSubmitted' : bigint,
  'ptmAttended' : bigint,
  'completionPercent' : bigint,
}
export interface ParentFeedback {
  'id' : string,
  'teacherId' : string,
  'teacherName' : string,
  'parentUsername' : string,
  'studentName' : string,
  'rating' : bigint,
  'comment' : string,
  'submittedAt' : string,
}
export interface PTMRecord {
  'id' : string,
  'teacherId' : string,
  'date' : string,
  'title' : string,
  'attendees' : string,
  'notes' : string,
}
export interface ClassActivity {
  'id' : string,
  'classGrade' : string,
  'teacherId' : string,
  'teacherName' : string,
  'branchId' : string,
  'date' : string,
  'title' : string,
  'description' : string,
  'mediaUrls' : Array<string>,
  'createdAt' : string,
}
export interface FormQuestion {
  'id' : string,
  'questionText' : string,
  'questionType' : string,
  'options' : Array<string>,
  'required' : boolean,
}
export interface FormAnswer {
  'questionId' : string,
  'questionText' : string,
  'answer' : string,
}
export interface SchoolForm {
  'id' : string,
  'title' : string,
  'description' : string,
  'questions' : Array<FormQuestion>,
  'publishedAt' : string,
  'isDraft' : boolean,
  'createdBy' : string,
  'responseCount' : bigint,
}
export interface FormResponse {
  'id' : string,
  'formId' : string,
  'parentUsername' : string,
  'studentName' : string,
  'answers' : Array<FormAnswer>,
  'submittedAt' : string,
}
export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'category' : string,
  'authorName' : string,
  'publishedAt' : string,
  'isDraft' : boolean,
  'tags' : string,
}
export interface ParentNotification {
  'id' : string,
  'parentUsername' : string,
  'title' : string,
  'message' : string,
  'notifType' : string,
  'isRead' : boolean,
  'createdAt' : string,
  'linkId' : string,
}

export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  // Staff Profiles
  'addStaffProfile' : ActorMethod<[StaffProfile], string>,
  'addUserAccount' : ActorMethod<[UserAccount], string>,
  'deleteStaffProfile' : ActorMethod<[string], undefined>,
  'deleteUserAccount' : ActorMethod<[string], undefined>,
  'getStaffProfiles' : ActorMethod<[], Array<StaffProfile>>,
  'getStaffProfilesByBranch' : ActorMethod<[string], Array<StaffProfile>>,
  'getStaffProfilesByRole' : ActorMethod<[string], Array<StaffProfile>>,
  'getUserAccounts' : ActorMethod<[], Array<UserAccount>>,
  'updateStaffProfile' : ActorMethod<[StaffProfile], undefined>,
  'updateUserAccount' : ActorMethod<[UserAccount], undefined>,
  // Core
  'addBranch' : ActorMethod<[Branch], string>,
  'addCalendarEvent' : ActorMethod<[CalendarEvent], string>,
  'addCampaign' : ActorMethod<[Campaign], string>,
  'addCampaignSend' : ActorMethod<[CampaignSend], string>,
  'addCampaignTemplate' : ActorMethod<[CampaignTemplate], string>,
  'addFollowUp' : ActorMethod<[FollowUp], string>,
  'addLead' : ActorMethod<[Lead], string>,
  'addLeadActivity' : ActorMethod<[LeadActivity], string>,
  'addLeadNote' : ActorMethod<[LeadNote], string>,
  'addLeadSource' : ActorMethod<[LeadSource], string>,
  'addReportCard' : ActorMethod<[ReportCard], string>,
  'addSchoolUpdate' : ActorMethod<[SchoolUpdate], string>,
  'addStudent' : ActorMethod<[Student], string>,
  'addTask' : ActorMethod<[Task], string>,
  'addTeacher' : ActorMethod<[Teacher], string>,
  'addTeamMember' : ActorMethod<[TeamMember], string>,
  'addWorksheet' : ActorMethod<[Worksheet], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBranch' : ActorMethod<[string], undefined>,
  'deleteCalendarEvent' : ActorMethod<[string], undefined>,
  'deleteCampaign' : ActorMethod<[string], undefined>,
  'deleteCampaignTemplate' : ActorMethod<[string], undefined>,
  'deleteFollowUp' : ActorMethod<[string], undefined>,
  'deleteLead' : ActorMethod<[string], undefined>,
  'deleteLeadActivity' : ActorMethod<[string], undefined>,
  'deleteLeadNote' : ActorMethod<[string], undefined>,
  'deleteLeadSource' : ActorMethod<[string], undefined>,
  'deleteReportCard' : ActorMethod<[string], undefined>,
  'deleteSchoolUpdate' : ActorMethod<[string], undefined>,
  'deleteStudent' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'deleteTeacher' : ActorMethod<[string], undefined>,
  'deleteTeamMember' : ActorMethod<[string], undefined>,
  'deleteWorksheet' : ActorMethod<[string], undefined>,
  'getActivitiesByLead' : ActorMethod<[string], Array<LeadActivity>>,
  'getAllLeadActivities' : ActorMethod<[], Array<LeadActivity>>,
  'getAllReportCards' : ActorMethod<[], Array<ReportCard>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAllWorksheets' : ActorMethod<[], Array<Worksheet>>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCampaignSends' : ActorMethod<[], Array<CampaignSend>>,
  'getCampaignSendsByCampaign' : ActorMethod<[string], Array<CampaignSend>>,
  'getCampaignSendsByLead' : ActorMethod<[string], Array<CampaignSend>>,
  'getCampaignTemplates' : ActorMethod<[], Array<CampaignTemplate>>,
  'getCampaigns' : ActorMethod<[], Array<Campaign>>,
  'getFollowUps' : ActorMethod<[], Array<FollowUp>>,
  'getIntegrationConfig' : ActorMethod<[], [] | [IntegrationConfig]>,
  'getLeadSources' : ActorMethod<[], Array<LeadSource>>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getNotesByLead' : ActorMethod<[string], Array<LeadNote>>,
  'getReportCardsByStudent' : ActorMethod<[string], Array<ReportCard>>,
  'getSchoolUpdates' : ActorMethod<[], Array<SchoolUpdate>>,
  'getStudentsByGrade' : ActorMethod<[string], Array<Student>>,
  'getStudentsByParent' : ActorMethod<[string], Array<Student>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getTasksByAssignee' : ActorMethod<[string], Array<Task>>,
  'getTasksByLead' : ActorMethod<[string], Array<Task>>,
  'getTeacherByUsername' : ActorMethod<[string], [] | [Teacher]>,
  'getTeachersByBranch' : ActorMethod<[string], Array<Teacher>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorksheetsByGrade' : ActorMethod<[string], Array<Worksheet>>,
  'initSeedData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [{ 'username' : string, 'password' : string }],
    [] | [{ 'username' : string, 'name' : string, 'role' : string }]
  >,
  'receiveWebhookLead' : ActorMethod<
    [
      {
        'source' : string,
        'name' : string,
        'email' : string,
        'gradeLevel' : string,
        'notes' : string,
        'phone' : string,
      },
    ],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveIntegrationConfig' : ActorMethod<[IntegrationConfig], undefined>,
  'searchLeads' : ActorMethod<[string], Array<Lead>>,
  'searchTasks' : ActorMethod<[string], Array<Task>>,
  'sendWhatsAppMessage' : ActorMethod<[string, string], WhatsAppMessageResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBranch' : ActorMethod<[Branch], undefined>,
  'updateCalendarEvent' : ActorMethod<[CalendarEvent], undefined>,
  'updateCampaign' : ActorMethod<[Campaign], undefined>,
  'updateCampaignTemplate' : ActorMethod<[CampaignTemplate], undefined>,
  'updateFollowUp' : ActorMethod<[FollowUp], undefined>,
  'updateLead' : ActorMethod<[Lead], undefined>,
  'updateLeadSource' : ActorMethod<[LeadSource], undefined>,
  'updateReportCard' : ActorMethod<[ReportCard], undefined>,
  'updateSchoolUpdate' : ActorMethod<[SchoolUpdate], undefined>,
  'updateStudent' : ActorMethod<[Student], undefined>,
  'updateTask' : ActorMethod<[Task], undefined>,
  'updateTeacher' : ActorMethod<[Teacher], undefined>,
  'updateTeamMember' : ActorMethod<[TeamMember], undefined>,
  'updateWorksheet' : ActorMethod<[Worksheet], undefined>,
  // Student Records
  'addStudentRecord' : ActorMethod<[StudentRecord], string>,
  'addStudentRecordsBulk' : ActorMethod<[Array<StudentRecord>], Array<string>>,
  'updateStudentRecord' : ActorMethod<[StudentRecord], undefined>,
  'deleteStudentRecord' : ActorMethod<[string], undefined>,
  'getAllStudentRecords' : ActorMethod<[], Array<StudentRecord>>,
  'getStudentRecordsByGrade' : ActorMethod<[string], Array<StudentRecord>>,
  'getStudentRecordsByBranch' : ActorMethod<[string], Array<StudentRecord>>,
  // WhatsApp History
  'getWhatsAppMessages' : ActorMethod<[], Array<WhatsAppMessage>>,
  'getWhatsAppMessagesByLead' : ActorMethod<[string], Array<WhatsAppMessage>>,
  'addWhatsAppMessage' : ActorMethod<[WhatsAppMessage], string>,
  'updateWhatsAppMessageStatus' : ActorMethod<[string, string], undefined>,
  // Staff Attendance
  'getStaffAttendance' : ActorMethod<[], Array<StaffAttendance>>,
  'getStaffAttendanceByDate' : ActorMethod<[string], Array<StaffAttendance>>,
  'getStaffAttendanceByStaff' : ActorMethod<[string], Array<StaffAttendance>>,
  'markAttendance' : ActorMethod<[StaffAttendance], string>,
  'updateAttendance' : ActorMethod<[StaffAttendance], undefined>,
  // Teacher Performance
  'getTeacherPerformanceRecords' : ActorMethod<[], Array<TeacherPerformanceRecord>>,
  'getTeacherPerformanceByTeacher' : ActorMethod<[string], Array<TeacherPerformanceRecord>>,
  'getParentFeedback' : ActorMethod<[], Array<ParentFeedback>>,
  'getParentFeedbackByTeacher' : ActorMethod<[string], Array<ParentFeedback>>,
  'submitParentFeedback' : ActorMethod<[ParentFeedback], string>,
  'getPTMRecords' : ActorMethod<[], Array<PTMRecord>>,
  'getPTMRecordsByTeacher' : ActorMethod<[string], Array<PTMRecord>>,
  'addPTMRecord' : ActorMethod<[PTMRecord], string>,
  // Classroom Activities
  'getAllClassActivities' : ActorMethod<[], Array<ClassActivity>>,
  'getClassActivitiesByGrade' : ActorMethod<[string], Array<ClassActivity>>,
  'getClassActivitiesByTeacher' : ActorMethod<[string], Array<ClassActivity>>,
  'getClassActivitiesByBranch' : ActorMethod<[string], Array<ClassActivity>>,
  'addClassActivity' : ActorMethod<[ClassActivity], string>,
  'updateClassActivity' : ActorMethod<[ClassActivity], undefined>,
  'deleteClassActivity' : ActorMethod<[string], undefined>,
  // Forms
  'getAllForms' : ActorMethod<[], Array<SchoolForm>>,
  'getPublishedForms' : ActorMethod<[], Array<SchoolForm>>,
  'getFormById' : ActorMethod<[string], [] | [SchoolForm]>,
  'addForm' : ActorMethod<[SchoolForm], string>,
  'updateForm' : ActorMethod<[SchoolForm], undefined>,
  'deleteForm' : ActorMethod<[string], undefined>,
  'getFormResponses' : ActorMethod<[string], Array<FormResponse>>,
  'getMyFormResponses' : ActorMethod<[string], Array<FormResponse>>,
  'submitFormResponse' : ActorMethod<[FormResponse], string>,
  // Blog
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'addBlogPost' : ActorMethod<[BlogPost], string>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  // Parent Notifications
  'getParentNotifications' : ActorMethod<[string], Array<ParentNotification>>,
  'addParentNotification' : ActorMethod<[ParentNotification], string>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
