/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'tags' : IDL.Text,
  'authorName' : IDL.Text,
  'publishedAt' : IDL.Text,
  'isDraft' : IDL.Bool,
  'category' : IDL.Text,
});
export const Branch = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'color' : IDL.Text,
  'category' : IDL.Text,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'description' : IDL.Text,
});
export const CampaignSend = IDL.Record({
  'id' : IDL.Text,
  'leadName' : IDL.Text,
  'templateId' : IDL.Text,
  'note' : IDL.Text,
  'campaignId' : IDL.Text,
  'sentAt' : IDL.Text,
  'sentBy' : IDL.Text,
  'leadId' : IDL.Text,
});
export const CampaignTemplate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'messageText' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const ClassActivity = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Text,
  'description' : IDL.Text,
  'teacherName' : IDL.Text,
  'teacherId' : IDL.Text,
  'mediaUrls' : IDL.Vec(IDL.Text),
  'branchId' : IDL.Text,
  'classGrade' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Text,
  'followUpType' : IDL.Text,
  'assignedTo' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'leadId' : IDL.Text,
  'notes' : IDL.Text,
});
export const FormQuestion = IDL.Record({
  'id' : IDL.Text,
  'questionText' : IDL.Text,
  'questionType' : IDL.Text,
  'required' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const SchoolForm = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdBy' : IDL.Text,
  'publishedAt' : IDL.Text,
  'description' : IDL.Text,
  'isDraft' : IDL.Bool,
  'questions' : IDL.Vec(FormQuestion),
  'responseCount' : IDL.Nat,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'source' : IDL.Text,
  'assignedAgent' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'email' : IDL.Text,
  'gradeLevel' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadActivity = IDL.Record({
  'id' : IDL.Text,
  'activityType' : IDL.Text,
  'description' : IDL.Text,
  'leadId' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : IDL.Text,
});
export const LeadNote = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Text,
  'createdBy' : IDL.Text,
  'leadId' : IDL.Text,
});
export const LeadSource = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const ParentNotification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'notifType' : IDL.Text,
  'createdAt' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'parentUsername' : IDL.Text,
  'linkId' : IDL.Text,
});
export const PTMRecord = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'teacherId' : IDL.Text,
  'attendees' : IDL.Text,
});
export const SubjectGrade = IDL.Record({
  'marks' : IDL.Text,
  'subject' : IDL.Text,
  'grade' : IDL.Text,
  'remarks' : IDL.Text,
});
export const ReportCard = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'subjects' : IDL.Vec(SubjectGrade),
  'date' : IDL.Text,
  'overallGrade' : IDL.Text,
  'term' : IDL.Text,
  'academicYear' : IDL.Text,
  'attendance' : IDL.Text,
  'teacherComment' : IDL.Text,
});
export const SchoolUpdate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'category' : IDL.Text,
});
export const StaffProfile = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'dailyActivities' : IDL.Text,
  'notes' : IDL.Text,
  'contactNumber' : IDL.Text,
  'branchId' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'grade' : IDL.Text,
  'parentUsername' : IDL.Text,
});
export const StudentRecord = IDL.Record({
  'id' : IDL.Text,
  'parentEmail' : IDL.Text,
  'parentContact' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'grade' : IDL.Text,
  'rollNumber' : IDL.Text,
  'address' : IDL.Text,
  'branchId' : IDL.Text,
  'parentName' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'leadId' : IDL.Text,
  'priority' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'subjects' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'branchId' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'branchId' : IDL.Text,
});
export const UserAccount = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
});
export const WhatsAppMessage = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'direction' : IDL.Text,
  'leadName' : IDL.Text,
  'messageId' : IDL.Text,
  'campaignId' : IDL.Text,
  'messageText' : IDL.Text,
  'leadId' : IDL.Text,
  'leadPhone' : IDL.Text,
  'timestamp' : IDL.Text,
});
export const WorksheetSubject = IDL.Record({
  'subject' : IDL.Text,
  'homework' : IDL.Text,
  'activities' : IDL.Text,
  'notes' : IDL.Text,
});
export const Worksheet = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subjects' : IDL.Vec(WorksheetSubject),
  'date' : IDL.Text,
  'teacherName' : IDL.Text,
  'grade' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const FormAnswer = IDL.Record({
  'answer' : IDL.Text,
  'questionText' : IDL.Text,
  'questionId' : IDL.Text,
});
export const FormResponse = IDL.Record({
  'id' : IDL.Text,
  'studentName' : IDL.Text,
  'answers' : IDL.Vec(FormAnswer),
  'submittedAt' : IDL.Text,
  'parentUsername' : IDL.Text,
  'formId' : IDL.Text,
});
export const IntegrationConfig = IDL.Record({
  'emailProvider' : IDL.Text,
  'whatsappAccessToken' : IDL.Text,
  'emailFromAddress' : IDL.Text,
  'emailApiKey' : IDL.Text,
  'whatsappApiUrl' : IDL.Text,
  'whatsappPhoneNumberId' : IDL.Text,
  'emailFromName' : IDL.Text,
  'websiteWebhookSecret' : IDL.Text,
  'metaWebhookVerifyToken' : IDL.Text,
});
export const ParentFeedback = IDL.Record({
  'id' : IDL.Text,
  'studentName' : IDL.Text,
  'submittedAt' : IDL.Text,
  'teacherName' : IDL.Text,
  'comment' : IDL.Text,
  'teacherId' : IDL.Text,
  'rating' : IDL.Nat,
  'parentUsername' : IDL.Text,
});
export const StaffAttendance = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'staffName' : IDL.Text,
  'staffId' : IDL.Text,
  'date' : IDL.Text,
  'markedBy' : IDL.Text,
  'timestamp' : IDL.Text,
  'branchId' : IDL.Text,
});
export const TeacherPerformanceRecord = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Text,
  'activitiesUploaded' : IDL.Nat,
  'year' : IDL.Text,
  'teacherName' : IDL.Text,
  'ptmAttended' : IDL.Nat,
  'completionPercent' : IDL.Nat,
  'teacherId' : IDL.Text,
  'branchId' : IDL.Text,
  'worksheetsSubmitted' : IDL.Nat,
});
export const WhatsAppMessageResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [IDL.Text], []),
  'addBranch' : IDL.Func([Branch], [IDL.Text], []),
  'addCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Text], []),
  'addCampaign' : IDL.Func([Campaign], [IDL.Text], []),
  'addCampaignSend' : IDL.Func([CampaignSend], [IDL.Text], []),
  'addCampaignTemplate' : IDL.Func([CampaignTemplate], [IDL.Text], []),
  'addClassActivity' : IDL.Func([ClassActivity], [IDL.Text], []),
  'addFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
  'addForm' : IDL.Func([SchoolForm], [IDL.Text], []),
  'addLead' : IDL.Func([Lead], [IDL.Text], []),
  'addLeadActivity' : IDL.Func([LeadActivity], [IDL.Text], []),
  'addLeadNote' : IDL.Func([LeadNote], [IDL.Text], []),
  'addLeadSource' : IDL.Func([LeadSource], [IDL.Text], []),
  'addNotification' : IDL.Func([ParentNotification], [IDL.Text], []),
  'addPTMRecord' : IDL.Func([PTMRecord], [IDL.Text], []),
  'addReportCard' : IDL.Func([ReportCard], [IDL.Text], []),
  'addSchoolUpdate' : IDL.Func([SchoolUpdate], [IDL.Text], []),
  'addStaffProfile' : IDL.Func([StaffProfile], [IDL.Text], []),
  'addStudent' : IDL.Func([Student], [IDL.Text], []),
  'addStudentRecord' : IDL.Func([StudentRecord], [IDL.Text], []),
  'addStudentRecordsBulk' : IDL.Func(
      [IDL.Vec(StudentRecord)],
      [IDL.Vec(IDL.Text)],
      [],
    ),
  'addTask' : IDL.Func([Task], [IDL.Text], []),
  'addTeacher' : IDL.Func([Teacher], [IDL.Text], []),
  'addTeamMember' : IDL.Func([TeamMember], [IDL.Text], []),
  'addUserAccount' : IDL.Func([UserAccount], [IDL.Text], []),
  'addWhatsAppMessage' : IDL.Func([WhatsAppMessage], [IDL.Text], []),
  'addWorksheet' : IDL.Func([Worksheet], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteBranch' : IDL.Func([IDL.Text], [], []),
  'deleteCalendarEvent' : IDL.Func([IDL.Text], [], []),
  'deleteCampaign' : IDL.Func([IDL.Text], [], []),
  'deleteCampaignTemplate' : IDL.Func([IDL.Text], [], []),
  'deleteClassActivity' : IDL.Func([IDL.Text], [], []),
  'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
  'deleteForm' : IDL.Func([IDL.Text], [], []),
  'deleteLead' : IDL.Func([IDL.Text], [], []),
  'deleteLeadActivity' : IDL.Func([IDL.Text], [], []),
  'deleteLeadNote' : IDL.Func([IDL.Text], [], []),
  'deleteLeadSource' : IDL.Func([IDL.Text], [], []),
  'deleteReportCard' : IDL.Func([IDL.Text], [], []),
  'deleteSchoolUpdate' : IDL.Func([IDL.Text], [], []),
  'deleteStaffProfile' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'deleteStudentRecord' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'deleteTeacher' : IDL.Func([IDL.Text], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'deleteUserAccount' : IDL.Func([IDL.Text], [], []),
  'deleteWorksheet' : IDL.Func([IDL.Text], [], []),
  'getActivitiesByLead' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeadActivity)],
      ['query'],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllClassActivities' : IDL.Func([], [IDL.Vec(ClassActivity)], ['query']),
  'getAllForms' : IDL.Func([], [IDL.Vec(SchoolForm)], ['query']),
  'getAllLeadActivities' : IDL.Func([], [IDL.Vec(LeadActivity)], ['query']),
  'getAllReportCards' : IDL.Func([], [IDL.Vec(ReportCard)], ['query']),
  'getAllStudentRecords' : IDL.Func([], [IDL.Vec(StudentRecord)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAllWorksheets' : IDL.Func([], [IDL.Vec(Worksheet)], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaignSends' : IDL.Func([], [IDL.Vec(CampaignSend)], ['query']),
  'getCampaignSendsByCampaign' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CampaignSend)],
      ['query'],
    ),
  'getCampaignSendsByLead' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CampaignSend)],
      ['query'],
    ),
  'getCampaignTemplates' : IDL.Func([], [IDL.Vec(CampaignTemplate)], ['query']),
  'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getClassActivitiesByBranch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClassActivity)],
      ['query'],
    ),
  'getClassActivitiesByGrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClassActivity)],
      ['query'],
    ),
  'getClassActivitiesByTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ClassActivity)],
      ['query'],
    ),
  'getFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getFormById' : IDL.Func([IDL.Text], [IDL.Opt(SchoolForm)], ['query']),
  'getFormResponses' : IDL.Func([IDL.Text], [IDL.Vec(FormResponse)], ['query']),
  'getIntegrationConfig' : IDL.Func(
      [],
      [IDL.Opt(IntegrationConfig)],
      ['query'],
    ),
  'getLeadSources' : IDL.Func([], [IDL.Vec(LeadSource)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getMyFormResponses' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FormResponse)],
      ['query'],
    ),
  'getNotesByLead' : IDL.Func([IDL.Text], [IDL.Vec(LeadNote)], ['query']),
  'getNotificationsForParent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ParentNotification)],
      ['query'],
    ),
  'getPTMRecords' : IDL.Func([], [IDL.Vec(PTMRecord)], ['query']),
  'getPTMRecordsByTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PTMRecord)],
      ['query'],
    ),
  'getParentFeedback' : IDL.Func([], [IDL.Vec(ParentFeedback)], ['query']),
  'getParentFeedbackByTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ParentFeedback)],
      ['query'],
    ),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getPublishedForms' : IDL.Func([], [IDL.Vec(SchoolForm)], ['query']),
  'getReportCardsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getSchoolUpdates' : IDL.Func([], [IDL.Vec(SchoolUpdate)], ['query']),
  'getStaffAttendance' : IDL.Func([], [IDL.Vec(StaffAttendance)], ['query']),
  'getStaffAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StaffAttendance)],
      ['query'],
    ),
  'getStaffAttendanceByStaff' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StaffAttendance)],
      ['query'],
    ),
  'getStaffProfiles' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'getStaffProfilesByBranch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StaffProfile)],
      ['query'],
    ),
  'getStaffProfilesByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StaffProfile)],
      ['query'],
    ),
  'getStudentRecordsByBranch' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentRecord)],
      ['query'],
    ),
  'getStudentRecordsByGrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentRecord)],
      ['query'],
    ),
  'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getStudentsByParent' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksByLead' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTeacherByUsername' : IDL.Func([IDL.Text], [IDL.Opt(Teacher)], ['query']),
  'getTeacherPerformanceByTeacher' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TeacherPerformanceRecord)],
      ['query'],
    ),
  'getTeacherPerformanceRecords' : IDL.Func(
      [],
      [IDL.Vec(TeacherPerformanceRecord)],
      ['query'],
    ),
  'getTeachersByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Teacher)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserAccounts' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsAppMessages' : IDL.Func([], [IDL.Vec(WhatsAppMessage)], ['query']),
  'getWhatsAppMessagesByLead' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WhatsAppMessage)],
      ['query'],
    ),
  'getWorksheetsByGrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Worksheet)],
      ['query'],
    ),
  'initSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
      [
        IDL.Opt(
          IDL.Record({
            'username' : IDL.Text,
            'name' : IDL.Text,
            'role' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'markAttendance' : IDL.Func([StaffAttendance], [IDL.Text], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'receiveWebhookLead' : IDL.Func(
      [
        IDL.Record({
          'source' : IDL.Text,
          'name' : IDL.Text,
          'email' : IDL.Text,
          'gradeLevel' : IDL.Text,
          'notes' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'receiveWhatsAppWebhook' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIntegrationConfig' : IDL.Func([IntegrationConfig], [], []),
  'searchLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'sendWhatsAppMessage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [WhatsAppMessageResult],
      [],
    ),
  'submitFormResponse' : IDL.Func([FormResponse], [IDL.Text], []),
  'submitParentFeedback' : IDL.Func([ParentFeedback], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAttendance' : IDL.Func([StaffAttendance], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateBranch' : IDL.Func([Branch], [], []),
  'updateCalendarEvent' : IDL.Func([CalendarEvent], [], []),
  'updateCampaign' : IDL.Func([Campaign], [], []),
  'updateCampaignTemplate' : IDL.Func([CampaignTemplate], [], []),
  'updateClassActivity' : IDL.Func([ClassActivity], [], []),
  'updateFollowUp' : IDL.Func([FollowUp], [], []),
  'updateForm' : IDL.Func([SchoolForm], [], []),
  'updateLead' : IDL.Func([Lead], [], []),
  'updateLeadSource' : IDL.Func([LeadSource], [], []),
  'updateReportCard' : IDL.Func([ReportCard], [], []),
  'updateSchoolUpdate' : IDL.Func([SchoolUpdate], [], []),
  'updateStaffProfile' : IDL.Func([StaffProfile], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
  'updateStudentRecord' : IDL.Func([StudentRecord], [], []),
  'updateTask' : IDL.Func([Task], [], []),
  'updateTeacher' : IDL.Func([Teacher], [], []),
  'updateTeamMember' : IDL.Func([TeamMember], [], []),
  'updateUserAccount' : IDL.Func([UserAccount], [], []),
  'updateWhatsAppMessageStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateWorksheet' : IDL.Func([Worksheet], [], []),
  'upsertTeacherPerformance' : IDL.Func(
      [TeacherPerformanceRecord],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'tags' : IDL.Text,
    'authorName' : IDL.Text,
    'publishedAt' : IDL.Text,
    'isDraft' : IDL.Bool,
    'category' : IDL.Text,
  });
  const Branch = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'color' : IDL.Text,
    'category' : IDL.Text,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'description' : IDL.Text,
  });
  const CampaignSend = IDL.Record({
    'id' : IDL.Text,
    'leadName' : IDL.Text,
    'templateId' : IDL.Text,
    'note' : IDL.Text,
    'campaignId' : IDL.Text,
    'sentAt' : IDL.Text,
    'sentBy' : IDL.Text,
    'leadId' : IDL.Text,
  });
  const CampaignTemplate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'messageText' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const ClassActivity = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Text,
    'description' : IDL.Text,
    'teacherName' : IDL.Text,
    'teacherId' : IDL.Text,
    'mediaUrls' : IDL.Vec(IDL.Text),
    'branchId' : IDL.Text,
    'classGrade' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Text,
    'followUpType' : IDL.Text,
    'assignedTo' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'leadId' : IDL.Text,
    'notes' : IDL.Text,
  });
  const FormQuestion = IDL.Record({
    'id' : IDL.Text,
    'questionText' : IDL.Text,
    'questionType' : IDL.Text,
    'required' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const SchoolForm = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdBy' : IDL.Text,
    'publishedAt' : IDL.Text,
    'description' : IDL.Text,
    'isDraft' : IDL.Bool,
    'questions' : IDL.Vec(FormQuestion),
    'responseCount' : IDL.Nat,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'source' : IDL.Text,
    'assignedAgent' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'email' : IDL.Text,
    'gradeLevel' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadActivity = IDL.Record({
    'id' : IDL.Text,
    'activityType' : IDL.Text,
    'description' : IDL.Text,
    'leadId' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : IDL.Text,
  });
  const LeadNote = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Text,
    'createdBy' : IDL.Text,
    'leadId' : IDL.Text,
  });
  const LeadSource = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const ParentNotification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'notifType' : IDL.Text,
    'createdAt' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'parentUsername' : IDL.Text,
    'linkId' : IDL.Text,
  });
  const PTMRecord = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'teacherId' : IDL.Text,
    'attendees' : IDL.Text,
  });
  const SubjectGrade = IDL.Record({
    'marks' : IDL.Text,
    'subject' : IDL.Text,
    'grade' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const ReportCard = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'subjects' : IDL.Vec(SubjectGrade),
    'date' : IDL.Text,
    'overallGrade' : IDL.Text,
    'term' : IDL.Text,
    'academicYear' : IDL.Text,
    'attendance' : IDL.Text,
    'teacherComment' : IDL.Text,
  });
  const SchoolUpdate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'category' : IDL.Text,
  });
  const StaffProfile = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'dailyActivities' : IDL.Text,
    'notes' : IDL.Text,
    'contactNumber' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'grade' : IDL.Text,
    'parentUsername' : IDL.Text,
  });
  const StudentRecord = IDL.Record({
    'id' : IDL.Text,
    'parentEmail' : IDL.Text,
    'parentContact' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'grade' : IDL.Text,
    'rollNumber' : IDL.Text,
    'address' : IDL.Text,
    'branchId' : IDL.Text,
    'parentName' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'leadId' : IDL.Text,
    'priority' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'subjects' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const UserAccount = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
  });
  const WhatsAppMessage = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'direction' : IDL.Text,
    'leadName' : IDL.Text,
    'messageId' : IDL.Text,
    'campaignId' : IDL.Text,
    'messageText' : IDL.Text,
    'leadId' : IDL.Text,
    'leadPhone' : IDL.Text,
    'timestamp' : IDL.Text,
  });
  const WorksheetSubject = IDL.Record({
    'subject' : IDL.Text,
    'homework' : IDL.Text,
    'activities' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Worksheet = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subjects' : IDL.Vec(WorksheetSubject),
    'date' : IDL.Text,
    'teacherName' : IDL.Text,
    'grade' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const FormAnswer = IDL.Record({
    'answer' : IDL.Text,
    'questionText' : IDL.Text,
    'questionId' : IDL.Text,
  });
  const FormResponse = IDL.Record({
    'id' : IDL.Text,
    'studentName' : IDL.Text,
    'answers' : IDL.Vec(FormAnswer),
    'submittedAt' : IDL.Text,
    'parentUsername' : IDL.Text,
    'formId' : IDL.Text,
  });
  const IntegrationConfig = IDL.Record({
    'emailProvider' : IDL.Text,
    'whatsappAccessToken' : IDL.Text,
    'emailFromAddress' : IDL.Text,
    'emailApiKey' : IDL.Text,
    'whatsappApiUrl' : IDL.Text,
    'whatsappPhoneNumberId' : IDL.Text,
    'emailFromName' : IDL.Text,
    'websiteWebhookSecret' : IDL.Text,
    'metaWebhookVerifyToken' : IDL.Text,
  });
  const ParentFeedback = IDL.Record({
    'id' : IDL.Text,
    'studentName' : IDL.Text,
    'submittedAt' : IDL.Text,
    'teacherName' : IDL.Text,
    'comment' : IDL.Text,
    'teacherId' : IDL.Text,
    'rating' : IDL.Nat,
    'parentUsername' : IDL.Text,
  });
  const StaffAttendance = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'staffName' : IDL.Text,
    'staffId' : IDL.Text,
    'date' : IDL.Text,
    'markedBy' : IDL.Text,
    'timestamp' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const TeacherPerformanceRecord = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Text,
    'activitiesUploaded' : IDL.Nat,
    'year' : IDL.Text,
    'teacherName' : IDL.Text,
    'ptmAttended' : IDL.Nat,
    'completionPercent' : IDL.Nat,
    'teacherId' : IDL.Text,
    'branchId' : IDL.Text,
    'worksheetsSubmitted' : IDL.Nat,
  });
  const WhatsAppMessageResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [IDL.Text], []),
    'addBranch' : IDL.Func([Branch], [IDL.Text], []),
    'addCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Text], []),
    'addCampaign' : IDL.Func([Campaign], [IDL.Text], []),
    'addCampaignSend' : IDL.Func([CampaignSend], [IDL.Text], []),
    'addCampaignTemplate' : IDL.Func([CampaignTemplate], [IDL.Text], []),
    'addClassActivity' : IDL.Func([ClassActivity], [IDL.Text], []),
    'addFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
    'addForm' : IDL.Func([SchoolForm], [IDL.Text], []),
    'addLead' : IDL.Func([Lead], [IDL.Text], []),
    'addLeadActivity' : IDL.Func([LeadActivity], [IDL.Text], []),
    'addLeadNote' : IDL.Func([LeadNote], [IDL.Text], []),
    'addLeadSource' : IDL.Func([LeadSource], [IDL.Text], []),
    'addNotification' : IDL.Func([ParentNotification], [IDL.Text], []),
    'addPTMRecord' : IDL.Func([PTMRecord], [IDL.Text], []),
    'addReportCard' : IDL.Func([ReportCard], [IDL.Text], []),
    'addSchoolUpdate' : IDL.Func([SchoolUpdate], [IDL.Text], []),
    'addStaffProfile' : IDL.Func([StaffProfile], [IDL.Text], []),
    'addStudent' : IDL.Func([Student], [IDL.Text], []),
    'addStudentRecord' : IDL.Func([StudentRecord], [IDL.Text], []),
    'addStudentRecordsBulk' : IDL.Func(
        [IDL.Vec(StudentRecord)],
        [IDL.Vec(IDL.Text)],
        [],
      ),
    'addTask' : IDL.Func([Task], [IDL.Text], []),
    'addTeacher' : IDL.Func([Teacher], [IDL.Text], []),
    'addTeamMember' : IDL.Func([TeamMember], [IDL.Text], []),
    'addUserAccount' : IDL.Func([UserAccount], [IDL.Text], []),
    'addWhatsAppMessage' : IDL.Func([WhatsAppMessage], [IDL.Text], []),
    'addWorksheet' : IDL.Func([Worksheet], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteBranch' : IDL.Func([IDL.Text], [], []),
    'deleteCalendarEvent' : IDL.Func([IDL.Text], [], []),
    'deleteCampaign' : IDL.Func([IDL.Text], [], []),
    'deleteCampaignTemplate' : IDL.Func([IDL.Text], [], []),
    'deleteClassActivity' : IDL.Func([IDL.Text], [], []),
    'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
    'deleteForm' : IDL.Func([IDL.Text], [], []),
    'deleteLead' : IDL.Func([IDL.Text], [], []),
    'deleteLeadActivity' : IDL.Func([IDL.Text], [], []),
    'deleteLeadNote' : IDL.Func([IDL.Text], [], []),
    'deleteLeadSource' : IDL.Func([IDL.Text], [], []),
    'deleteReportCard' : IDL.Func([IDL.Text], [], []),
    'deleteSchoolUpdate' : IDL.Func([IDL.Text], [], []),
    'deleteStaffProfile' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'deleteStudentRecord' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'deleteTeacher' : IDL.Func([IDL.Text], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'deleteUserAccount' : IDL.Func([IDL.Text], [], []),
    'deleteWorksheet' : IDL.Func([IDL.Text], [], []),
    'getActivitiesByLead' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeadActivity)],
        ['query'],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllClassActivities' : IDL.Func([], [IDL.Vec(ClassActivity)], ['query']),
    'getAllForms' : IDL.Func([], [IDL.Vec(SchoolForm)], ['query']),
    'getAllLeadActivities' : IDL.Func([], [IDL.Vec(LeadActivity)], ['query']),
    'getAllReportCards' : IDL.Func([], [IDL.Vec(ReportCard)], ['query']),
    'getAllStudentRecords' : IDL.Func([], [IDL.Vec(StudentRecord)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAllWorksheets' : IDL.Func([], [IDL.Vec(Worksheet)], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaignSends' : IDL.Func([], [IDL.Vec(CampaignSend)], ['query']),
    'getCampaignSendsByCampaign' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CampaignSend)],
        ['query'],
      ),
    'getCampaignSendsByLead' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CampaignSend)],
        ['query'],
      ),
    'getCampaignTemplates' : IDL.Func(
        [],
        [IDL.Vec(CampaignTemplate)],
        ['query'],
      ),
    'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getClassActivitiesByBranch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClassActivity)],
        ['query'],
      ),
    'getClassActivitiesByGrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClassActivity)],
        ['query'],
      ),
    'getClassActivitiesByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ClassActivity)],
        ['query'],
      ),
    'getFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getFormById' : IDL.Func([IDL.Text], [IDL.Opt(SchoolForm)], ['query']),
    'getFormResponses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FormResponse)],
        ['query'],
      ),
    'getIntegrationConfig' : IDL.Func(
        [],
        [IDL.Opt(IntegrationConfig)],
        ['query'],
      ),
    'getLeadSources' : IDL.Func([], [IDL.Vec(LeadSource)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getMyFormResponses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FormResponse)],
        ['query'],
      ),
    'getNotesByLead' : IDL.Func([IDL.Text], [IDL.Vec(LeadNote)], ['query']),
    'getNotificationsForParent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ParentNotification)],
        ['query'],
      ),
    'getPTMRecords' : IDL.Func([], [IDL.Vec(PTMRecord)], ['query']),
    'getPTMRecordsByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PTMRecord)],
        ['query'],
      ),
    'getParentFeedback' : IDL.Func([], [IDL.Vec(ParentFeedback)], ['query']),
    'getParentFeedbackByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ParentFeedback)],
        ['query'],
      ),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getPublishedForms' : IDL.Func([], [IDL.Vec(SchoolForm)], ['query']),
    'getReportCardsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getSchoolUpdates' : IDL.Func([], [IDL.Vec(SchoolUpdate)], ['query']),
    'getStaffAttendance' : IDL.Func([], [IDL.Vec(StaffAttendance)], ['query']),
    'getStaffAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StaffAttendance)],
        ['query'],
      ),
    'getStaffAttendanceByStaff' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StaffAttendance)],
        ['query'],
      ),
    'getStaffProfiles' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'getStaffProfilesByBranch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StaffProfile)],
        ['query'],
      ),
    'getStaffProfilesByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StaffProfile)],
        ['query'],
      ),
    'getStudentRecordsByBranch' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentRecord)],
        ['query'],
      ),
    'getStudentRecordsByGrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentRecord)],
        ['query'],
      ),
    'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getStudentsByParent' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksByLead' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTeacherByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Teacher)],
        ['query'],
      ),
    'getTeacherPerformanceByTeacher' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TeacherPerformanceRecord)],
        ['query'],
      ),
    'getTeacherPerformanceRecords' : IDL.Func(
        [],
        [IDL.Vec(TeacherPerformanceRecord)],
        ['query'],
      ),
    'getTeachersByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Teacher)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserAccounts' : IDL.Func([], [IDL.Vec(UserAccount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsAppMessages' : IDL.Func([], [IDL.Vec(WhatsAppMessage)], ['query']),
    'getWhatsAppMessagesByLead' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WhatsAppMessage)],
        ['query'],
      ),
    'getWorksheetsByGrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Worksheet)],
        ['query'],
      ),
    'initSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
        [
          IDL.Opt(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'markAttendance' : IDL.Func([StaffAttendance], [IDL.Text], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'receiveWebhookLead' : IDL.Func(
        [
          IDL.Record({
            'source' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'gradeLevel' : IDL.Text,
            'notes' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'receiveWhatsAppWebhook' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIntegrationConfig' : IDL.Func([IntegrationConfig], [], []),
    'searchLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'sendWhatsAppMessage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [WhatsAppMessageResult],
        [],
      ),
    'submitFormResponse' : IDL.Func([FormResponse], [IDL.Text], []),
    'submitParentFeedback' : IDL.Func([ParentFeedback], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAttendance' : IDL.Func([StaffAttendance], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateBranch' : IDL.Func([Branch], [], []),
    'updateCalendarEvent' : IDL.Func([CalendarEvent], [], []),
    'updateCampaign' : IDL.Func([Campaign], [], []),
    'updateCampaignTemplate' : IDL.Func([CampaignTemplate], [], []),
    'updateClassActivity' : IDL.Func([ClassActivity], [], []),
    'updateFollowUp' : IDL.Func([FollowUp], [], []),
    'updateForm' : IDL.Func([SchoolForm], [], []),
    'updateLead' : IDL.Func([Lead], [], []),
    'updateLeadSource' : IDL.Func([LeadSource], [], []),
    'updateReportCard' : IDL.Func([ReportCard], [], []),
    'updateSchoolUpdate' : IDL.Func([SchoolUpdate], [], []),
    'updateStaffProfile' : IDL.Func([StaffProfile], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
    'updateStudentRecord' : IDL.Func([StudentRecord], [], []),
    'updateTask' : IDL.Func([Task], [], []),
    'updateTeacher' : IDL.Func([Teacher], [], []),
    'updateTeamMember' : IDL.Func([TeamMember], [], []),
    'updateUserAccount' : IDL.Func([UserAccount], [], []),
    'updateWhatsAppMessageStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateWorksheet' : IDL.Func([Worksheet], [], []),
    'upsertTeacherPerformance' : IDL.Func(
        [TeacherPerformanceRecord],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };