/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Branch = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});
export const CalendarEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'color' : IDL.Text,
  'category' : IDL.Text,
});
export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'description' : IDL.Text,
});
export const CampaignSend = IDL.Record({
  'id' : IDL.Text,
  'leadName' : IDL.Text,
  'templateId' : IDL.Text,
  'note' : IDL.Text,
  'campaignId' : IDL.Text,
  'sentAt' : IDL.Text,
  'sentBy' : IDL.Text,
  'leadId' : IDL.Text,
});
export const CampaignTemplate = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'mediaUrl' : IDL.Text,
  'messageText' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const FollowUp = IDL.Record({
  'id' : IDL.Text,
  'followUpType' : IDL.Text,
  'assignedTo' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'leadId' : IDL.Text,
  'notes' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'source' : IDL.Text,
  'assignedAgent' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Text,
  'email' : IDL.Text,
  'gradeLevel' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const LeadActivity = IDL.Record({
  'id' : IDL.Text,
  'activityType' : IDL.Text,
  'description' : IDL.Text,
  'leadId' : IDL.Text,
  'performedBy' : IDL.Text,
  'timestamp' : IDL.Text,
});
export const LeadNote = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Text,
  'createdBy' : IDL.Text,
  'leadId' : IDL.Text,
});
export const LeadSource = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const SubjectGrade = IDL.Record({
  'marks' : IDL.Text,
  'subject' : IDL.Text,
  'grade' : IDL.Text,
  'remarks' : IDL.Text,
});
export const ReportCard = IDL.Record({
  'id' : IDL.Text,
  'studentId' : IDL.Text,
  'subjects' : IDL.Vec(SubjectGrade),
  'date' : IDL.Text,
  'overallGrade' : IDL.Text,
  'term' : IDL.Text,
  'academicYear' : IDL.Text,
  'attendance' : IDL.Text,
  'teacherComment' : IDL.Text,
});
export const SchoolUpdate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'category' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'admissionNumber' : IDL.Text,
  'grade' : IDL.Text,
  'parentUsername' : IDL.Text,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'assignedTo' : IDL.Text,
  'createdAt' : IDL.Text,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Text,
  'description' : IDL.Text,
  'leadId' : IDL.Text,
  'priority' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'subjects' : IDL.Text,
  'name' : IDL.Text,
  'grade' : IDL.Text,
  'branchId' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'branchId' : IDL.Text,
});
export const WorksheetSubject = IDL.Record({
  'subject' : IDL.Text,
  'homework' : IDL.Text,
  'activities' : IDL.Text,
  'notes' : IDL.Text,
});
export const Worksheet = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subjects' : IDL.Vec(WorksheetSubject),
  'date' : IDL.Text,
  'teacherName' : IDL.Text,
  'grade' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const IntegrationConfig = IDL.Record({
  'emailProvider' : IDL.Text,
  'whatsappAccessToken' : IDL.Text,
  'emailFromAddress' : IDL.Text,
  'emailApiKey' : IDL.Text,
  'whatsappApiUrl' : IDL.Text,
  'whatsappPhoneNumberId' : IDL.Text,
  'emailFromName' : IDL.Text,
  'websiteWebhookSecret' : IDL.Text,
  'metaWebhookVerifyToken' : IDL.Text,
});
export const WhatsAppMessageResult = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBranch' : IDL.Func([Branch], [IDL.Text], []),
  'addCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Text], []),
  'addCampaign' : IDL.Func([Campaign], [IDL.Text], []),
  'addCampaignSend' : IDL.Func([CampaignSend], [IDL.Text], []),
  'addCampaignTemplate' : IDL.Func([CampaignTemplate], [IDL.Text], []),
  'addFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
  'addLead' : IDL.Func([Lead], [IDL.Text], []),
  'addLeadActivity' : IDL.Func([LeadActivity], [IDL.Text], []),
  'addLeadNote' : IDL.Func([LeadNote], [IDL.Text], []),
  'addLeadSource' : IDL.Func([LeadSource], [IDL.Text], []),
  'addReportCard' : IDL.Func([ReportCard], [IDL.Text], []),
  'addSchoolUpdate' : IDL.Func([SchoolUpdate], [IDL.Text], []),
  'addStudent' : IDL.Func([Student], [IDL.Text], []),
  'addTask' : IDL.Func([Task], [IDL.Text], []),
  'addTeacher' : IDL.Func([Teacher], [IDL.Text], []),
  'addTeamMember' : IDL.Func([TeamMember], [IDL.Text], []),
  'addWorksheet' : IDL.Func([Worksheet], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBranch' : IDL.Func([IDL.Text], [], []),
  'deleteCalendarEvent' : IDL.Func([IDL.Text], [], []),
  'deleteCampaign' : IDL.Func([IDL.Text], [], []),
  'deleteCampaignTemplate' : IDL.Func([IDL.Text], [], []),
  'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
  'deleteLead' : IDL.Func([IDL.Text], [], []),
  'deleteLeadActivity' : IDL.Func([IDL.Text], [], []),
  'deleteLeadNote' : IDL.Func([IDL.Text], [], []),
  'deleteLeadSource' : IDL.Func([IDL.Text], [], []),
  'deleteReportCard' : IDL.Func([IDL.Text], [], []),
  'deleteSchoolUpdate' : IDL.Func([IDL.Text], [], []),
  'deleteStudent' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'deleteTeacher' : IDL.Func([IDL.Text], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
  'deleteWorksheet' : IDL.Func([IDL.Text], [], []),
  'getActivitiesByLead' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LeadActivity)],
      ['query'],
    ),
  'getAllLeadActivities' : IDL.Func([], [IDL.Vec(LeadActivity)], ['query']),
  'getAllReportCards' : IDL.Func([], [IDL.Vec(ReportCard)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAllWorksheets' : IDL.Func([], [IDL.Vec(Worksheet)], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCampaignSends' : IDL.Func([], [IDL.Vec(CampaignSend)], ['query']),
  'getCampaignSendsByCampaign' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CampaignSend)],
      ['query'],
    ),
  'getCampaignSendsByLead' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CampaignSend)],
      ['query'],
    ),
  'getCampaignTemplates' : IDL.Func([], [IDL.Vec(CampaignTemplate)], ['query']),
  'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
  'getIntegrationConfig' : IDL.Func(
      [],
      [IDL.Opt(IntegrationConfig)],
      ['query'],
    ),
  'getLeadSources' : IDL.Func([], [IDL.Vec(LeadSource)], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getNotesByLead' : IDL.Func([IDL.Text], [IDL.Vec(LeadNote)], ['query']),
  'getReportCardsByStudent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReportCard)],
      ['query'],
    ),
  'getSchoolUpdates' : IDL.Func([], [IDL.Vec(SchoolUpdate)], ['query']),
  'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getStudentsByParent' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTasksByLead' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getTeacherByUsername' : IDL.Func([IDL.Text], [IDL.Opt(Teacher)], ['query']),
  'getTeachersByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Teacher)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorksheetsByGrade' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Worksheet)],
      ['query'],
    ),
  'initSeedData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
      [
        IDL.Opt(
          IDL.Record({
            'username' : IDL.Text,
            'name' : IDL.Text,
            'role' : IDL.Text,
          })
        ),
      ],
      [],
    ),
  'receiveWebhookLead' : IDL.Func(
      [
        IDL.Record({
          'source' : IDL.Text,
          'name' : IDL.Text,
          'email' : IDL.Text,
          'gradeLevel' : IDL.Text,
          'notes' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveIntegrationConfig' : IDL.Func([IntegrationConfig], [], []),
  'searchLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
  'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'sendWhatsAppMessage' : IDL.Func(
      [IDL.Text, IDL.Text],
      [WhatsAppMessageResult],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBranch' : IDL.Func([Branch], [], []),
  'updateCalendarEvent' : IDL.Func([CalendarEvent], [], []),
  'updateCampaign' : IDL.Func([Campaign], [], []),
  'updateCampaignTemplate' : IDL.Func([CampaignTemplate], [], []),
  'updateFollowUp' : IDL.Func([FollowUp], [], []),
  'updateLead' : IDL.Func([Lead], [], []),
  'updateLeadSource' : IDL.Func([LeadSource], [], []),
  'updateReportCard' : IDL.Func([ReportCard], [], []),
  'updateSchoolUpdate' : IDL.Func([SchoolUpdate], [], []),
  'updateStudent' : IDL.Func([Student], [], []),
  'updateTask' : IDL.Func([Task], [], []),
  'updateTeacher' : IDL.Func([Teacher], [], []),
  'updateTeamMember' : IDL.Func([TeamMember], [], []),
  'updateWorksheet' : IDL.Func([Worksheet], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Branch = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  const CalendarEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'color' : IDL.Text,
    'category' : IDL.Text,
  });
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'description' : IDL.Text,
  });
  const CampaignSend = IDL.Record({
    'id' : IDL.Text,
    'leadName' : IDL.Text,
    'templateId' : IDL.Text,
    'note' : IDL.Text,
    'campaignId' : IDL.Text,
    'sentAt' : IDL.Text,
    'sentBy' : IDL.Text,
    'leadId' : IDL.Text,
  });
  const CampaignTemplate = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'mediaUrl' : IDL.Text,
    'messageText' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const FollowUp = IDL.Record({
    'id' : IDL.Text,
    'followUpType' : IDL.Text,
    'assignedTo' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'leadId' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'source' : IDL.Text,
    'assignedAgent' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Text,
    'email' : IDL.Text,
    'gradeLevel' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const LeadActivity = IDL.Record({
    'id' : IDL.Text,
    'activityType' : IDL.Text,
    'description' : IDL.Text,
    'leadId' : IDL.Text,
    'performedBy' : IDL.Text,
    'timestamp' : IDL.Text,
  });
  const LeadNote = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Text,
    'createdBy' : IDL.Text,
    'leadId' : IDL.Text,
  });
  const LeadSource = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const SubjectGrade = IDL.Record({
    'marks' : IDL.Text,
    'subject' : IDL.Text,
    'grade' : IDL.Text,
    'remarks' : IDL.Text,
  });
  const ReportCard = IDL.Record({
    'id' : IDL.Text,
    'studentId' : IDL.Text,
    'subjects' : IDL.Vec(SubjectGrade),
    'date' : IDL.Text,
    'overallGrade' : IDL.Text,
    'term' : IDL.Text,
    'academicYear' : IDL.Text,
    'attendance' : IDL.Text,
    'teacherComment' : IDL.Text,
  });
  const SchoolUpdate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'category' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'admissionNumber' : IDL.Text,
    'grade' : IDL.Text,
    'parentUsername' : IDL.Text,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'assignedTo' : IDL.Text,
    'createdAt' : IDL.Text,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Text,
    'description' : IDL.Text,
    'leadId' : IDL.Text,
    'priority' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'subjects' : IDL.Text,
    'name' : IDL.Text,
    'grade' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'branchId' : IDL.Text,
  });
  const WorksheetSubject = IDL.Record({
    'subject' : IDL.Text,
    'homework' : IDL.Text,
    'activities' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Worksheet = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subjects' : IDL.Vec(WorksheetSubject),
    'date' : IDL.Text,
    'teacherName' : IDL.Text,
    'grade' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const IntegrationConfig = IDL.Record({
    'emailProvider' : IDL.Text,
    'whatsappAccessToken' : IDL.Text,
    'emailFromAddress' : IDL.Text,
    'emailApiKey' : IDL.Text,
    'whatsappApiUrl' : IDL.Text,
    'whatsappPhoneNumberId' : IDL.Text,
    'emailFromName' : IDL.Text,
    'websiteWebhookSecret' : IDL.Text,
    'metaWebhookVerifyToken' : IDL.Text,
  });
  const WhatsAppMessageResult = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBranch' : IDL.Func([Branch], [IDL.Text], []),
    'addCalendarEvent' : IDL.Func([CalendarEvent], [IDL.Text], []),
    'addCampaign' : IDL.Func([Campaign], [IDL.Text], []),
    'addCampaignSend' : IDL.Func([CampaignSend], [IDL.Text], []),
    'addCampaignTemplate' : IDL.Func([CampaignTemplate], [IDL.Text], []),
    'addFollowUp' : IDL.Func([FollowUp], [IDL.Text], []),
    'addLead' : IDL.Func([Lead], [IDL.Text], []),
    'addLeadActivity' : IDL.Func([LeadActivity], [IDL.Text], []),
    'addLeadNote' : IDL.Func([LeadNote], [IDL.Text], []),
    'addLeadSource' : IDL.Func([LeadSource], [IDL.Text], []),
    'addReportCard' : IDL.Func([ReportCard], [IDL.Text], []),
    'addSchoolUpdate' : IDL.Func([SchoolUpdate], [IDL.Text], []),
    'addStudent' : IDL.Func([Student], [IDL.Text], []),
    'addTask' : IDL.Func([Task], [IDL.Text], []),
    'addTeacher' : IDL.Func([Teacher], [IDL.Text], []),
    'addTeamMember' : IDL.Func([TeamMember], [IDL.Text], []),
    'addWorksheet' : IDL.Func([Worksheet], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBranch' : IDL.Func([IDL.Text], [], []),
    'deleteCalendarEvent' : IDL.Func([IDL.Text], [], []),
    'deleteCampaign' : IDL.Func([IDL.Text], [], []),
    'deleteCampaignTemplate' : IDL.Func([IDL.Text], [], []),
    'deleteFollowUp' : IDL.Func([IDL.Text], [], []),
    'deleteLead' : IDL.Func([IDL.Text], [], []),
    'deleteLeadActivity' : IDL.Func([IDL.Text], [], []),
    'deleteLeadNote' : IDL.Func([IDL.Text], [], []),
    'deleteLeadSource' : IDL.Func([IDL.Text], [], []),
    'deleteReportCard' : IDL.Func([IDL.Text], [], []),
    'deleteSchoolUpdate' : IDL.Func([IDL.Text], [], []),
    'deleteStudent' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'deleteTeacher' : IDL.Func([IDL.Text], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Text], [], []),
    'deleteWorksheet' : IDL.Func([IDL.Text], [], []),
    'getActivitiesByLead' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LeadActivity)],
        ['query'],
      ),
    'getAllLeadActivities' : IDL.Func([], [IDL.Vec(LeadActivity)], ['query']),
    'getAllReportCards' : IDL.Func([], [IDL.Vec(ReportCard)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAllWorksheets' : IDL.Func([], [IDL.Vec(Worksheet)], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCampaignSends' : IDL.Func([], [IDL.Vec(CampaignSend)], ['query']),
    'getCampaignSendsByCampaign' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CampaignSend)],
        ['query'],
      ),
    'getCampaignSendsByLead' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CampaignSend)],
        ['query'],
      ),
    'getCampaignTemplates' : IDL.Func(
        [],
        [IDL.Vec(CampaignTemplate)],
        ['query'],
      ),
    'getCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getFollowUps' : IDL.Func([], [IDL.Vec(FollowUp)], ['query']),
    'getIntegrationConfig' : IDL.Func(
        [],
        [IDL.Opt(IntegrationConfig)],
        ['query'],
      ),
    'getLeadSources' : IDL.Func([], [IDL.Vec(LeadSource)], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getNotesByLead' : IDL.Func([IDL.Text], [IDL.Vec(LeadNote)], ['query']),
    'getReportCardsByStudent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReportCard)],
        ['query'],
      ),
    'getSchoolUpdates' : IDL.Func([], [IDL.Vec(SchoolUpdate)], ['query']),
    'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getStudentsByParent' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTasksByAssignee' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTasksByLead' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getTeacherByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Teacher)],
        ['query'],
      ),
    'getTeachersByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Teacher)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorksheetsByGrade' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Worksheet)],
        ['query'],
      ),
    'initSeedData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Record({ 'username' : IDL.Text, 'password' : IDL.Text })],
        [
          IDL.Opt(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
        ],
        [],
      ),
    'receiveWebhookLead' : IDL.Func(
        [
          IDL.Record({
            'source' : IDL.Text,
            'name' : IDL.Text,
            'email' : IDL.Text,
            'gradeLevel' : IDL.Text,
            'notes' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveIntegrationConfig' : IDL.Func([IntegrationConfig], [], []),
    'searchLeads' : IDL.Func([IDL.Text], [IDL.Vec(Lead)], ['query']),
    'searchTasks' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'sendWhatsAppMessage' : IDL.Func(
        [IDL.Text, IDL.Text],
        [WhatsAppMessageResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBranch' : IDL.Func([Branch], [], []),
    'updateCalendarEvent' : IDL.Func([CalendarEvent], [], []),
    'updateCampaign' : IDL.Func([Campaign], [], []),
    'updateCampaignTemplate' : IDL.Func([CampaignTemplate], [], []),
    'updateFollowUp' : IDL.Func([FollowUp], [], []),
    'updateLead' : IDL.Func([Lead], [], []),
    'updateLeadSource' : IDL.Func([LeadSource], [], []),
    'updateReportCard' : IDL.Func([ReportCard], [], []),
    'updateSchoolUpdate' : IDL.Func([SchoolUpdate], [], []),
    'updateStudent' : IDL.Func([Student], [], []),
    'updateTask' : IDL.Func([Task], [], []),
    'updateTeacher' : IDL.Func([Teacher], [], []),
    'updateTeamMember' : IDL.Func([TeamMember], [], []),
    'updateWorksheet' : IDL.Func([Worksheet], [], []),
  });
};

export const init = ({ IDL }) => { return []; };