/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeadNote {
    id: string;
    content: string;
    createdAt: string;
    createdBy: string;
    leadId: string;
}
export interface Branch {
    id: string;
    name: string;
    location: string;
}
export interface Worksheet {
    id: string;
    title: string;
    subjects: Array<WorksheetSubject>;
    date: string;
    teacherName: string;
    grade: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ReportCard {
    id: string;
    studentId: string;
    subjects: Array<SubjectGrade>;
    date: string;
    overallGrade: string;
    term: string;
    academicYear: string;
    attendance: string;
    teacherComment: string;
}
export interface LeadActivity {
    id: string;
    activityType: string;
    description: string;
    leadId: string;
    performedBy: string;
    timestamp: string;
}
export interface Task {
    id: string;
    title: string;
    assignedTo: string;
    createdAt: string;
    completed: boolean;
    dueDate: string;
    description: string;
    leadId: string;
    priority: string;
}
export interface LeadSource {
    id: string;
    name: string;
}
export interface Teacher {
    id: string;
    username: string;
    subjects: string;
    name: string;
    grade: string;
    branchId: string;
}
export interface SubjectGrade {
    marks: string;
    subject: string;
    grade: string;
    remarks: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface Lead {
    id: string;
    status: string;
    source: string;
    assignedAgent: string;
    name: string;
    createdAt: string;
    email: string;
    gradeLevel: string;
    notes: string;
    phone: string;
}
export interface CampaignSend {
    id: string;
    leadName: string;
    templateId: string;
    note: string;
    campaignId: string;
    sentAt: string;
    sentBy: string;
    leadId: string;
}
export interface CalendarEvent {
    id: string;
    title: string;
    date: string;
    color: string;
    category: string;
}
export interface CampaignTemplate {
    id: string;
    name: string;
    createdAt: string;
    mediaUrl: string;
    messageText: string;
    mediaType: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface IntegrationConfig {
    emailProvider: string;
    whatsappAccessToken: string;
    emailFromAddress: string;
    emailApiKey: string;
    whatsappApiUrl: string;
    whatsappPhoneNumberId: string;
    emailFromName: string;
    websiteWebhookSecret: string;
    metaWebhookVerifyToken: string;
}
export interface SchoolUpdate {
    id: string;
    title: string;
    content: string;
    date: string;
    category: string;
}
export interface TeamMember {
    id: string;
    name: string;
    role: string;
    branchId: string;
}
export interface FollowUp {
    id: string;
    followUpType: string;
    assignedTo: string;
    completed: boolean;
    dueDate: string;
    leadId: string;
    notes: string;
}
export interface Campaign {
    id: string;
    status: string;
    name: string;
    createdAt: string;
    description: string;
}
export interface WorksheetSubject {
    subject: string;
    homework: string;
    activities: string;
    notes: string;
}
export interface WhatsAppMessageResult {
    message: string;
    success: boolean;
}
export interface UserProfile {
    name: string;
    role: string;
    email: string;
}
export interface Student {
    id: string;
    name: string;
    admissionNumber: string;
    grade: string;
    parentUsername: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBranch(b: Branch): Promise<string>;
    addCalendarEvent(e: CalendarEvent): Promise<string>;
    addCampaign(c: Campaign): Promise<string>;
    addCampaignSend(s: CampaignSend): Promise<string>;
    addCampaignTemplate(t: CampaignTemplate): Promise<string>;
    addFollowUp(fu: FollowUp): Promise<string>;
    addLead(lead: Lead): Promise<string>;
    addLeadActivity(a: LeadActivity): Promise<string>;
    addLeadNote(n: LeadNote): Promise<string>;
    addLeadSource(s: LeadSource): Promise<string>;
    addReportCard(rc: ReportCard): Promise<string>;
    addSchoolUpdate(u: SchoolUpdate): Promise<string>;
    addStudent(s: Student): Promise<string>;
    addTask(t: Task): Promise<string>;
    addTeacher(t: Teacher): Promise<string>;
    addTeamMember(m: TeamMember): Promise<string>;
    addWorksheet(w: Worksheet): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBranch(id: string): Promise<void>;
    deleteCalendarEvent(id: string): Promise<void>;
    deleteCampaign(id: string): Promise<void>;
    deleteCampaignTemplate(id: string): Promise<void>;
    deleteFollowUp(id: string): Promise<void>;
    deleteLead(id: string): Promise<void>;
    deleteLeadActivity(id: string): Promise<void>;
    deleteLeadNote(id: string): Promise<void>;
    deleteLeadSource(id: string): Promise<void>;
    deleteReportCard(id: string): Promise<void>;
    deleteSchoolUpdate(id: string): Promise<void>;
    deleteStudent(id: string): Promise<void>;
    deleteTask(id: string): Promise<void>;
    deleteTeacher(id: string): Promise<void>;
    deleteTeamMember(id: string): Promise<void>;
    deleteWorksheet(id: string): Promise<void>;
    getActivitiesByLead(leadId: string): Promise<Array<LeadActivity>>;
    getAllLeadActivities(): Promise<Array<LeadActivity>>;
    getAllReportCards(): Promise<Array<ReportCard>>;
    getAllStudents(): Promise<Array<Student>>;
    getAllTeachers(): Promise<Array<Teacher>>;
    getAllWorksheets(): Promise<Array<Worksheet>>;
    getBranches(): Promise<Array<Branch>>;
    getCalendarEvents(): Promise<Array<CalendarEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCampaignSends(): Promise<Array<CampaignSend>>;
    getCampaignSendsByCampaign(campaignId: string): Promise<Array<CampaignSend>>;
    getCampaignSendsByLead(leadId: string): Promise<Array<CampaignSend>>;
    getCampaignTemplates(): Promise<Array<CampaignTemplate>>;
    getCampaigns(): Promise<Array<Campaign>>;
    getFollowUps(): Promise<Array<FollowUp>>;
    getIntegrationConfig(): Promise<IntegrationConfig | null>;
    getLeadSources(): Promise<Array<LeadSource>>;
    getLeads(): Promise<Array<Lead>>;
    getNotesByLead(leadId: string): Promise<Array<LeadNote>>;
    getReportCardsByStudent(studentId: string): Promise<Array<ReportCard>>;
    getSchoolUpdates(): Promise<Array<SchoolUpdate>>;
    getStudentsByGrade(grade: string): Promise<Array<Student>>;
    getStudentsByParent(parentUsername: string): Promise<Array<Student>>;
    getTasks(): Promise<Array<Task>>;
    getTasksByAssignee(assignedTo: string): Promise<Array<Task>>;
    getTasksByLead(leadId: string): Promise<Array<Task>>;
    getTeacherByUsername(username: string): Promise<Teacher | null>;
    getTeachersByBranch(branchId: string): Promise<Array<Teacher>>;
    getTeamMembers(): Promise<Array<TeamMember>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorksheetsByGrade(grade: string): Promise<Array<Worksheet>>;
    initSeedData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    login(credentials: {
        username: string;
        password: string;
    }): Promise<{
        username: string;
        name: string;
        role: string;
    } | null>;
    receiveWebhookLead(payload: {
        source: string;
        name: string;
        email: string;
        gradeLevel: string;
        notes: string;
        phone: string;
    }): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveIntegrationConfig(config: IntegrationConfig): Promise<void>;
    searchLeads(term: string): Promise<Array<Lead>>;
    searchTasks(term: string): Promise<Array<Task>>;
    sendWhatsAppMessage(to: string, message: string): Promise<WhatsAppMessageResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBranch(b: Branch): Promise<void>;
    updateCalendarEvent(e: CalendarEvent): Promise<void>;
    updateCampaign(c: Campaign): Promise<void>;
    updateCampaignTemplate(t: CampaignTemplate): Promise<void>;
    updateFollowUp(fu: FollowUp): Promise<void>;
    updateLead(lead: Lead): Promise<void>;
    updateLeadSource(s: LeadSource): Promise<void>;
    updateReportCard(rc: ReportCard): Promise<void>;
    updateSchoolUpdate(u: SchoolUpdate): Promise<void>;
    updateStudent(s: Student): Promise<void>;
    updateTask(t: Task): Promise<void>;
    updateTeacher(t: Teacher): Promise<void>;
    updateTeamMember(m: TeamMember): Promise<void>;
    updateWorksheet(w: Worksheet): Promise<void>;
}
import type { IntegrationConfig as _IntegrationConfig, Teacher as _Teacher, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBranch(arg0: Branch): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBranch(arg0);
            return result;
        }
    }
    async addCalendarEvent(arg0: CalendarEvent): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalendarEvent(arg0);
            return result;
        }
    }
    async addCampaign(arg0: Campaign): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCampaign(arg0);
            return result;
        }
    }
    async addCampaignSend(arg0: CampaignSend): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCampaignSend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCampaignSend(arg0);
            return result;
        }
    }
    async addCampaignTemplate(arg0: CampaignTemplate): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addCampaignTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCampaignTemplate(arg0);
            return result;
        }
    }
    async addFollowUp(arg0: FollowUp): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFollowUp(arg0);
            return result;
        }
    }
    async addLead(arg0: Lead): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(arg0);
            return result;
        }
    }
    async addLeadActivity(arg0: LeadActivity): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadActivity(arg0);
            return result;
        }
    }
    async addLeadNote(arg0: LeadNote): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadNote(arg0);
            return result;
        }
    }
    async addLeadSource(arg0: LeadSource): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeadSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeadSource(arg0);
            return result;
        }
    }
    async addReportCard(arg0: ReportCard): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReportCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReportCard(arg0);
            return result;
        }
    }
    async addSchoolUpdate(arg0: SchoolUpdate): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSchoolUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSchoolUpdate(arg0);
            return result;
        }
    }
    async addStudent(arg0: Student): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudent(arg0);
            return result;
        }
    }
    async addTask(arg0: Task): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0);
            return result;
        }
    }
    async addTeacher(arg0: Teacher): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeacher(arg0);
            return result;
        }
    }
    async addTeamMember(arg0: TeamMember): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeamMember(arg0);
            return result;
        }
    }
    async addWorksheet(arg0: Worksheet): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorksheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorksheet(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBranch(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBranch(arg0);
            return result;
        }
    }
    async deleteCalendarEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEvent(arg0);
            return result;
        }
    }
    async deleteCampaign(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaign(arg0);
            return result;
        }
    }
    async deleteCampaignTemplate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCampaignTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCampaignTemplate(arg0);
            return result;
        }
    }
    async deleteFollowUp(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFollowUp(arg0);
            return result;
        }
    }
    async deleteLead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLead(arg0);
            return result;
        }
    }
    async deleteLeadActivity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeadActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeadActivity(arg0);
            return result;
        }
    }
    async deleteLeadNote(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeadNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeadNote(arg0);
            return result;
        }
    }
    async deleteLeadSource(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeadSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeadSource(arg0);
            return result;
        }
    }
    async deleteReportCard(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReportCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReportCard(arg0);
            return result;
        }
    }
    async deleteSchoolUpdate(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSchoolUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSchoolUpdate(arg0);
            return result;
        }
    }
    async deleteStudent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async deleteTeacher(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeacher(arg0);
            return result;
        }
    }
    async deleteTeamMember(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeamMember(arg0);
            return result;
        }
    }
    async deleteWorksheet(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorksheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorksheet(arg0);
            return result;
        }
    }
    async getActivitiesByLead(arg0: string): Promise<Array<LeadActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivitiesByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivitiesByLead(arg0);
            return result;
        }
    }
    async getAllLeadActivities(): Promise<Array<LeadActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeadActivities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeadActivities();
            return result;
        }
    }
    async getAllReportCards(): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReportCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReportCards();
            return result;
        }
    }
    async getAllStudents(): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents();
            return result;
        }
    }
    async getAllTeachers(): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeachers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeachers();
            return result;
        }
    }
    async getAllWorksheets(): Promise<Array<Worksheet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorksheets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorksheets();
            return result;
        }
    }
    async getBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranches();
            return result;
        }
    }
    async getCalendarEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEvents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCampaignSends(): Promise<Array<CampaignSend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignSends();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignSends();
            return result;
        }
    }
    async getCampaignSendsByCampaign(arg0: string): Promise<Array<CampaignSend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignSendsByCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignSendsByCampaign(arg0);
            return result;
        }
    }
    async getCampaignSendsByLead(arg0: string): Promise<Array<CampaignSend>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignSendsByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignSendsByLead(arg0);
            return result;
        }
    }
    async getCampaignTemplates(): Promise<Array<CampaignTemplate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaignTemplates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaignTemplates();
            return result;
        }
    }
    async getCampaigns(): Promise<Array<Campaign>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCampaigns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCampaigns();
            return result;
        }
    }
    async getFollowUps(): Promise<Array<FollowUp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowUps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowUps();
            return result;
        }
    }
    async getIntegrationConfig(): Promise<IntegrationConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntegrationConfig();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntegrationConfig();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeadSources(): Promise<Array<LeadSource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeadSources();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeadSources();
            return result;
        }
    }
    async getLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return result;
        }
    }
    async getNotesByLead(arg0: string): Promise<Array<LeadNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotesByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotesByLead(arg0);
            return result;
        }
    }
    async getReportCardsByStudent(arg0: string): Promise<Array<ReportCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportCardsByStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportCardsByStudent(arg0);
            return result;
        }
    }
    async getSchoolUpdates(): Promise<Array<SchoolUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSchoolUpdates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSchoolUpdates();
            return result;
        }
    }
    async getStudentsByGrade(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByGrade(arg0);
            return result;
        }
    }
    async getStudentsByParent(arg0: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentsByParent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentsByParent(arg0);
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return result;
        }
    }
    async getTasksByAssignee(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByAssignee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByAssignee(arg0);
            return result;
        }
    }
    async getTasksByLead(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByLead(arg0);
            return result;
        }
    }
    async getTeacherByUsername(arg0: string): Promise<Teacher | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherByUsername(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherByUsername(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeachersByBranch(arg0: string): Promise<Array<Teacher>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeachersByBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeachersByBranch(arg0);
            return result;
        }
    }
    async getTeamMembers(): Promise<Array<TeamMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamMembers();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorksheetsByGrade(arg0: string): Promise<Array<Worksheet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorksheetsByGrade(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorksheetsByGrade(arg0);
            return result;
        }
    }
    async initSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeedData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: {
        username: string;
        password: string;
    }): Promise<{
        username: string;
        name: string;
        role: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async receiveWebhookLead(arg0: {
        source: string;
        name: string;
        email: string;
        gradeLevel: string;
        notes: string;
        phone: string;
    }): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.receiveWebhookLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.receiveWebhookLead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveIntegrationConfig(arg0: IntegrationConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveIntegrationConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveIntegrationConfig(arg0);
            return result;
        }
    }
    async searchLeads(arg0: string): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLeads(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLeads(arg0);
            return result;
        }
    }
    async searchTasks(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTasks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTasks(arg0);
            return result;
        }
    }
    async sendWhatsAppMessage(arg0: string, arg1: string): Promise<WhatsAppMessageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendWhatsAppMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendWhatsAppMessage(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBranch(arg0: Branch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0);
            return result;
        }
    }
    async updateCalendarEvent(arg0: CalendarEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEvent(arg0);
            return result;
        }
    }
    async updateCampaign(arg0: Campaign): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaign(arg0);
            return result;
        }
    }
    async updateCampaignTemplate(arg0: CampaignTemplate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCampaignTemplate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCampaignTemplate(arg0);
            return result;
        }
    }
    async updateFollowUp(arg0: FollowUp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFollowUp(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFollowUp(arg0);
            return result;
        }
    }
    async updateLead(arg0: Lead): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0);
            return result;
        }
    }
    async updateLeadSource(arg0: LeadSource): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadSource(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadSource(arg0);
            return result;
        }
    }
    async updateReportCard(arg0: ReportCard): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReportCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReportCard(arg0);
            return result;
        }
    }
    async updateSchoolUpdate(arg0: SchoolUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSchoolUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSchoolUpdate(arg0);
            return result;
        }
    }
    async updateStudent(arg0: Student): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStudent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStudent(arg0);
            return result;
        }
    }
    async updateTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0);
            return result;
        }
    }
    async updateTeacher(arg0: Teacher): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeacher(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeacher(arg0);
            return result;
        }
    }
    async updateTeamMember(arg0: TeamMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamMember(arg0);
            return result;
        }
    }
    async updateWorksheet(arg0: Worksheet): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorksheet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorksheet(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IntegrationConfig]): IntegrationConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Teacher]): Teacher | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        username: string;
        name: string;
        role: string;
    }]): {
    username: string;
    name: string;
    role: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
